export const THEMES = {
  light: {
    name: 'light',
    page: 'min-h-screen bg-white',
    shell: 'w-full max-w-6xl mx-auto px-6 py-10',
    card: 'bg-white p-4 border border-gray-300 rounded',
    h1: 'text-2xl font-semibold text-gray-900',
    h2: 'text-lg font-semibold text-gray-900',
    text: 'text-gray-800',
    muted: 'text-gray-600',
    axis: '#6b7280',
    grid: '#e5e7eb',
    cloud: '#1c4c74',
    edge: '#349ce4',
    kpiValue: 'text-gray-900 font-semibold',
    kpiSub: 'text-sm text-gray-600',
    kpiCard: 'bg-white p-4 border border-gray-300 rounded',
    btn: 'inline-flex items-center gap-2 rounded px-3 py-2 text-sm border border-gray-400 text-gray-800 bg-white hover:bg-gray-100',
    btnPrimary: 'inline-flex items-center gap-2 rounded px-3 py-2 text-sm border border-gray-900 text-gray-900 bg-white hover:bg-gray-100',
    btnGhost: 'inline-flex items-center gap-2 rounded px-3 py-2 text-sm border border-gray-400 text-gray-800 bg-white hover:bg-gray-100',
    pill: 'border border-gray-400 bg-white text-gray-800 rounded px-2 py-1 text-sm hover:bg-gray-100',
    accent: '#111827',
  },
};
